[TASK] Test in github action workflow xdebug

diff --git a/.github/workflows/docker-compose-test.yml b/.github/workflows/docker-compose-test.yml
--- a/.github/workflows/docker-compose-test.yml
+++ b/.github/workflows/docker-compose-test.yml
@@ -28,4 +28,18 @@ jobs:
             - name: Build and test services
               run: |
                   docker-compose -f docker-compose.yml up --build -d
-                  docker-compose -f docker-compose.yml down
+
+            -   name: Test Xdebug
+                run: |
+                    sleep 10 # Wait for the containers to fully initialize
+                    XDEBUG_OUTPUT=$(curl -s http://localhost/index.php)
+                    if [[ ! "$XDEBUG_OUTPUT" =~ "Xdebug" ]]; then
+                      echo "Xdebug test failed. Not found in phpinfo() output."
+                      exit 1
+                    else
+                      echo "Xdebug test successful."
+                    fi
+
+            -   name: Cleanup
+                run: |
+                    docker-compose -f docker-compose.yml down
